[package]
name = "dorea"
version = "0.2.1"
description = "A key-value stroage system"
repository = "https://github.com/mrxiaozhuox/Dorea/"
authors = ["mrxiaozhuox <mrxzx@wwsg18.top>"]
edition = "2018"
license = "MIT"
keywords = ["database","cache","storage"]
exclude = [
    ".DS_Store",
    ".idea/*",
    ".vscode/*"
]

[dependencies]
tokio = { version = "1.6.1", features = ['full'] }

# Serialize & Deserialize
serde = { version = "1.0.126", features = ['derive'] }
toml = "0.5.8"