[package]
name = "dorea"
version = "0.2.1"
description = "A key-value stroage system"
repository = "https://github.com/mrxiaozhuox/Dorea/"
authors = ["mrxiaozhuox <mrxzx@wwsg18.top>"]
edition = "2018"
license = "MIT"
keywords = ["database","cache","storage"]
exclude = [
    ".DS_Store",
    ".idea/*",
    ".vscode/*"
]

[dependencies]
tokio = { version = "1.6.1", features = ['full'] }

# LRU Queue
lru = "0.6.5"

# Bytes Tool
bytes = "1.0.1"

# Parsing Tool
nom = "6.2.1"

# Lazy Static
once_cell = "1.8.0"

# Directory Manager
dirs = "3.0.2"

# Time Manager
chrono = "0.4.19"

# Serialize & Deserialize
serde = { version = "1.0.126", features = ['derive'] }
serde_json = "1.0.64"
toml = "0.5.8"
bincode = "1.3.3"