[package]
name = "dorea"
version = "0.3.0"
description = "A key-value stroage system"
repository = "https://github.com/mrxiaozhuox/Dorea/"
authors = ["ZhuoEr Liu <mrxzx@wwsg18.top>"]
edition = "2018"
license = "MIT"
keywords = ["database","cache","storage"]
exclude = [
    ".DS_Store",
    ".idea/*",
    ".vscode/*"
]

[[bin]]
name = "dorea-server"
path = "src/bin/server.rs"

[features]

# default features: all feature.
default = ["server", "client"]

# server features: just run for server.
server = ["processor"]

# client features: client manager tools.
client = ["processor"]

# processor feature: include [value, network] to io data and fmt it.
processor = []

[dependencies]
tokio = { version = "1.6.1", features = ['full'] }
anyhow = "1.0.42"

# LRU Queue
lru = "0.6.5"

# Bytes Tool
bytes = "1.0.1"

# Parsing Tool
nom = "6.2.1"
clap = "2.33.3"

# Lazy Static
once_cell = "1.8.0"

# Directory Manager
dirs = "3.0.2"
walkdir = "2.3.2"

# Time Manager
chrono = "0.4.19"

# Serialize & Deserialize
serde = { version = "1.0.126", features = ['derive'] }
serde_json = "1.0.64"
toml = "0.5.8"
bincode = "1.3.3"

base64 = "0.13.0"
md5 = "0.7.0"
crc = "2.0.0"

# Logger Library
log = "0.4.14"
log4rs = "1.0.0"
