[package]
name = "dorea"
version = "0.1.0"
authors = ["mrxiaozhuox <mrxzx@wwsg18.top>"]
edition = "2018"
license = "MIT"
keywords = ["database","cache",]

[[bin]]
name = "dorea-cli"
path = "src/bin/client.rs"

[[bin]]
name = "dorea-server"
path = "src/bin/server.rs"

[dependencies]
tokio = { version = "1.6.1", features = ['full'] }
toml = "0.5.8"
chrono = "0.4.19"
once_cell = "1.7.2"
base64="0.13.0"
regex = "1.5.4"
clap = "2.33.3"
rustyline = "8.2.0"

log = "0.4.14"
log4rs = "1.0.0"

serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
bincode = "1.3.3"