[connection]
max_connect_number = 255
connection_password = ""

[database]
max_group_number = 20
default_group = "default"
readonly_group = ["dorea"]

[cache]
max_cache_number = 256
check_interval = 10000
