refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  operation:
    kind: rolling_file
    path: :DOREA_LOG_PATH:/operation.log
    encoder:
      pattern: "{d} - {m}{n}"
    policy:
      trigger: 
        kind: size
        limit: 20480
      roller:
        kind: delete
root:
  level: info
  appenders:
    - stdout
loggers:
  dorea::database:
    level: info
    appenders:
      - operation
    additive: false