[connection]
max_connect_number = 255
connection_password = ""

[database]
max_group_number = 20
default_group = "default"
pre_load_group = ["default", "system"]
max_key_number = 102400

[cache]
group_cache_size = 128
check_interval = 10000
